<शैली गुरु>
#समावेश <मानकपन.स>
#समावेश <माला.स>
#समावेश <मानकघोष.स>
#समावेश <मानककोष.स>
#समावेश <प्रकार.स>
#समावेश <unistd.h>
#समावेश <fcntl.h>
#समावेश <sys/ioctl.h>
#समावेश <termपन.स>
#समावेश <termios.h>

/* This file was generated by QuickBasic to C translator */
/* qb2c  ver.1.0 Jan-1996                                */

#घोषणा LMAX 1024

/* Function declarations */
बाह्य पूर्णांक    LEN(अक्षर *);
बाह्य अक्षर  *INKEY_S(व्योम);

/* Shared variables and arrays declarations */
अटल काष्ठा termio term_orig;
अटल पूर्णांक  kbdflgs;
अटल अक्षर   w__S[16][LMAX];
अटल पूर्णांक    j__S = 0;
अटल द्विगुन x__d[16];
अटल पूर्णांक    i__x = 0;
अटल अक्षर  *keys__S[]  = अणु"Spacebar",
"F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12",
"Insert", "Home", "PageUp",
"Delete", "End", "PageDown",
               "Arrow Up",
"Arrow Left", "Arrow Down", "Arrow Right" पूर्ण;
अटल पूर्णांक    n__keys = 23;

/* Open files poपूर्णांकers */
खाता *fp_1, *fp_2;

मुख्य()
अणु
 अटल पूर्णांक i, j, k=0, l=0;
 अटल अक्षर a_S[LMAX], tbl_S[LMAX];

 म_नकल(tbl_S,दो_पर्या("HOME"));
 म_जोड़ो(tbl_S,"/.kbcalib");
 अगर((fp_1 = ख_खोलो("calib.log", "w")) == शून्य)
 अणु
  ख_लिखो(मानक_त्रुटि,"calib: cant open file %s\n","calib.log"); निकास(0);
 पूर्ण
 अगर((fp_2 = ख_खोलो(tbl_S, "w")) == शून्य)
 अणु
  ख_लिखो(मानक_त्रुटि,"calib: cant create file %s\n",tbl_S); निकास(0);
 पूर्ण
 क्रम(j = 0; j < n__keys; j++)
 अणु
  अगर(j == n__keys) म_लिखो("Numerical keyboard:\n");
  म_लिखो("Press %s:\n",keys__S[j]);
  म_नकल(a_S,INKEY_S());
  अगर (j > 0) ख_लिखो(fp_2,"%s\n",a_S);
  ख_लिखो(fp_1,"%-12s",keys__S[j]);
  क्रम(i = 0; i <= LEN(a_S) - 1; i++)
  अणु
   ख_लिखो(fp_1,"%d ", a_S[i]);
  पूर्ण
  ख_लिखो(fp_1,"\n");
  अगर(म_भेद(a_S, "q") == 0) अणु जाओ Lab_999; पूर्ण
  क्रम (k=1; k<=32000; k=k+1) l=l+.5*2;  /* a small छोड़ो */
  म_लिखो("\b  OK!\n");
 पूर्ण
Lab_999:
 ख_बंद(fp_1);
 ख_बंद(fp_2);
 निकास(0);
पूर्ण /* End of MAIN */

/* Translates of used QB's पूर्णांकrinsic functions: */

बाह्य पूर्णांक LEN(अक्षर *a_S)
अणु
 अगर (++i__x == 16) i__x = 0;
 x__d[i__x] = म_माप(a_S);
 वापस x__d[i__x];
पूर्ण

बाह्य अक्षर  *INKEY_S(व्योम)
अणु
 अटल पूर्णांक i;

 अगर (++j__S == 16) j__S=0;
 input_mode();
 जबतक((i=पढ़ो(0,w__S[j__S],5)) < 1);
 w__S[j__S][i]=0;
 प्रणाली_mode();
 अगर (w__S[j__S][0] == 3) निकास(0);
 वापस w__S[j__S];
पूर्ण

पूर्णांक प्रणाली_mode(व्योम)
अणु
    अगर (ioctl(0, TCSETA, &term_orig) == -1) अणु
        वापस (0);
    पूर्ण
    fcntl(0, F_SETFL, kbdflgs);
पूर्ण

पूर्णांक input_mode(व्योम)
अणु
    अटल काष्ठा termio term;
    अटल पूर्णांक flags;

    अगर (ioctl(0, TCGETA, &term) == -1) अणु
        वापस (-1);
    पूर्ण
    (व्योम) ioctl(0, TCGETA, &term_orig);
    term.c_अगरlag = 0;
    term.c_oflag = 0;
    term.c_lflag = 0;
    term.c_cc[VMIN] = 1;
    term.c_cc[VTIME] = 0;
    अगर (ioctl(0, TCSETA, &term) == -1) अणु
        वापस (-1);
    पूर्ण
    kbdflgs = fcntl(0, F_GETFL, 0);
    flags = fcntl(0, F_GETFL);
    flags &= ~O_NDELAY;
    fcntl(0, F_SETFL, flags);
    वापस (0);
पूर्ण
